package spawner

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"strings"

	"github.com/creack/pty"
	"github.com/yashashkumar/ai-issue-agent/internal/models"
	"github.com/yashashkumar/ai-issue-agent/internal/repository"
)

type AgentProcess struct {
	logger    *slog.Logger
	agentRepo *repository.AgentRepo
}

func NewAgentProcess(logger *slog.Logger, agentRepo *repository.AgentRepo) *AgentProcess {
	return &AgentProcess{logger: logger, agentRepo: agentRepo}
}

type processExitError struct {
	code int
	pid  int
	err  error
}

func (e *processExitError) Error() string { return e.err.Error() }
func (e *processExitError) Code() int     { return e.code }
func (e *processExitError) Pid() int      { return e.pid }

func (p *AgentProcess) Run(ctx context.Context, req SpawnRequest) error {
	// First ensure workdir exists
	if err := os.MkdirAll(req.WorkDir, 0755); err != nil {
		return fmt.Errorf("failed to create workdir %s: %w", req.WorkDir, err)
	}

	// Optional: git branch setup
	if req.CreateBranch && req.BranchName != nil {
		RunGit(ctx, req.WorkDir, "checkout", "-b", *req.BranchName)
	}

	// Resolve gemini CLI path
	cliPath := os.Getenv("GEMINI_CLI_PATH")
	if cliPath == "" {
		cliPath = "gemini"
	}

	// Build the command — we use -y (YOLO) and pipe the prompt via -p flag
	// This avoids stdin-blocking that occurs when gemini tries to read more input
	cmd := exec.CommandContext(ctx, cliPath, "-y", "-p", req.SystemPrompt)
	cmd.Dir = req.WorkDir

	// Build subprocess env cleanly (deduplicating keys we override)
	nvmBin := "/Users/yashash_kumar/.nvm/versions/node/v24.1.0/bin"
	homeDir, _ := os.UserHomeDir()
	parentEnv := os.Environ()
	subEnv := make([]string, 0, len(parentEnv)+6)
	for _, e := range parentEnv {
		if strings.HasPrefix(e, "PATH=") ||
			strings.HasPrefix(e, "HOME=") ||
			strings.HasPrefix(e, "GEMINI_API_KEY=") ||
			strings.HasPrefix(e, "GEMINI_HOME=") ||
			strings.HasPrefix(e, "XDG_CONFIG_HOME=") ||
			strings.HasPrefix(e, "TERM=") {
			continue
		}
		subEnv = append(subEnv, e)
	}
	subEnv = append(subEnv,
		"PATH="+nvmBin+":"+os.Getenv("PATH"),
		"HOME="+homeDir,
		"GEMINI_HOME="+homeDir+"/.gemini",
		"XDG_CONFIG_HOME="+homeDir+"/.config",
		"GEMINI_API_KEY="+os.Getenv("GEMINI_API_KEY"),
		"NODE_NO_WARNINGS=1",
		// Provide a TERM so the TUI renders properly inside the PTY
		"TERM=xterm-256color",
	)
	cmd.Env = subEnv

	// Allocate a PTY — this makes gemini think it has a real terminal,
	// preventing the TUI from blocking or crashing due to missing TTY.
	// Note: pty.Start handles process group setup internally; do not set SysProcAttr.Setpgid.
	ptmx, err := pty.Start(cmd)
	if err != nil {
		return fmt.Errorf("failed to start agent process with pty: %w", err)
	}
	defer ptmx.Close()

	// Persist PID
	go p.agentRepo.UpdatePID(context.Background(), req.ID, cmd.Process.Pid)

	// Stream the PTY output (merged stdout+stderr from the pseudo-terminal)
	go p.streamLogs(req.ID, models.LogStreamStdout, ptmx)

	err = cmd.Wait()
	if err != nil {
		var code int
		if exitError, ok := err.(*exec.ExitError); ok {
			code = exitError.ExitCode()
		} else {
			code = -1
		}
		return &processExitError{code: code, pid: cmd.Process.Pid, err: err}
	}

	// Success — optionally commit and create PR for GitHub-sourced agents
	if req.Source == models.AgentSourceGitHubIssue || req.Source == models.AgentSourceGitHubComment {
		if req.CreatePR && req.BranchName != nil && req.GitHubOwner != nil && req.GitHubRepo != nil {
			branch := *req.BranchName
			repo := fmt.Sprintf("%s/%s", *req.GitHubOwner, *req.GitHubRepo)
			msg := fmt.Sprintf("fix: agent work for issue #%d", *req.GitHubIssueNumber)
			CommitAndPush(ctx, req.WorkDir, msg, branch)

			title := fmt.Sprintf("[Agent] Fix for #%d", *req.GitHubIssueNumber)
			body := fmt.Sprintf("Automatically generated by AgentForge.\nIssue: #%d\nAgent: %s", *req.GitHubIssueNumber, req.ID)
			CreatePR(ctx, req.WorkDir, title, body, "main", branch, repo)
		}
	}

	return nil
}

func (p *AgentProcess) streamLogs(agentID string, stream models.LogStream, r io.Reader) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := scanner.Text()
		// Strip ANSI escape codes for clean log storage
		line = stripANSI(line)
		if line == "" {
			continue
		}
		err := p.agentRepo.InsertLog(context.Background(), agentID, stream, line)
		if err != nil {
			p.logger.Error("failed to insert log line", "agent_id", agentID, "stream", stream, "err", err)
		}
	}
}

// stripANSI removes ANSI terminal escape sequences from TUI output
// so that stored logs are clean plain text.
func stripANSI(s string) string {
	var result strings.Builder
	i := 0
	for i < len(s) {
		if s[i] == '\x1b' && i+1 < len(s) && s[i+1] == '[' {
			// Skip until we hit a letter (end of escape sequence)
			i += 2
			for i < len(s) && (s[i] < 'A' || s[i] > 'z') {
				i++
			}
			if i < len(s) {
				i++ // skip the final letter
			}
		} else {
			result.WriteByte(s[i])
			i++
		}
	}
	return strings.TrimSpace(result.String())
}
